config: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
  _convert_dict: true
  _fields:
    data: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _convert_dict: true
      _fields:
        ambient_dim: 100
        create_dataset: false
        data_samples: 50000
        datamodule: KSphere
        dim: 100
        manifold_dim: 10
        n_spheres: 1
        noise_std: 0
        num_channels: 0
        shape:
        - 100
        split:
        - 0.8
        - 0.1
        - 0.1
        use_data_mean: false
      _locked: false
      _type_safe: true
    device: !!python/object/apply:torch.device
    - cpu
    eval: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _convert_dict: true
      _fields:
        batch_size: 512
        begin_ckpt: 50
        bpd_dataset: test
        callback: null
        enable_bpd: false
        enable_loss: true
        enable_sampling: true
        end_ckpt: 96
        num_samples: 50000
        workers: 4
      _locked: false
      _type_safe: true
    logging: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _convert_dict: true
      _fields:
        envery_timedelta: !!python/object/apply:datetime.timedelta
        - 0
        - 60
        - 0
        every_n_epochs: 1000
        log_name: ve
        log_path: test_logs/
        top_k: 5
      _locked: false
      _type_safe: true
    model: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _convert_dict: true
      _fields:
        checkpoint_path: null
        dropout: 0.0
        ema_rate: 0.9999
        hidden_layers: 3
        hidden_nodes: 512
        name: fcn
        num_scales: 1000
        scale_by_sigma: false
        sigma_max: 14.142135623730951
        sigma_min: 0.01
        state_size: 100
      _locked: false
      _type_safe: true
    optim: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _convert_dict: true
      _fields:
        beta1: 0.9
        eps: 1.0e-08
        grad_clip: 1.0
        lr: 2.0e-05
        optimizer: Adam
        warmup: 5000
        weight_decay: 0
      _locked: false
      _type_safe: true
    sampling: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _convert_dict: true
      _fields:
        corrector: none
        method: pc
        n_steps_each: 1
        noise_removal: true
        predictor: reverse_diffusion
        probability_flow: false
        snr: 0.15
      _locked: false
      _type_safe: true
    seed: 42
    training: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _convert_dict: true
      _fields:
        accelerator: null
        accumulate_grad_batches: 1
        batch_size: 500
        continuous: true
        eval_freq: 2500
        gpus: 0
        lightning_module: base
        likelihood_weighting: true
        log_freq: 50
        mode: train
        n_iters: 100000000000000000000
        num_epochs: 100000000000000000000
        num_nodes: 1
        reduce_mean: false
        sde: vesde
        show_evolution: false
        snapshot_freq: 5000
        snapshot_freq_for_preemption: 5000
        snapshot_sampling: true
        visualization_callback: null
        workers: 4
      _locked: false
      _type_safe: true
    validation: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _convert_dict: true
      _fields:
        batch_size: 500
        workers: 4
      _locked: false
      _type_safe: true
  _locked: false
  _type_safe: true
