config: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
  _convert_dict: true
  _fields:
    data: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _convert_dict: true
      _fields:
        base_dir: /store/CIA/js2164/data/
        centered: false
        create_dataset: false
        crop: true
        datamodule: unpaired_PKLDataset
        dataset: celeba
        effective_image_size: 64
        image_size: 64
        num_channels: 3
        scale: 4
        shape:
        - 3
        - 64
        - 64
        split:
        - 0.8
        - 0.1
        - 0.1
        task: generation
        uniform_dequantization: false
        use_data_mean: false
        use_flip: true
      _locked: false
      _type_safe: true
    device: !!python/object/apply:torch.device
    - cuda
    - 0
    eval: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _convert_dict: true
      _fields:
        batch_size: 50
        begin_ckpt: 50
        bpd_dataset: test
        callback: null
        enable_bpd: false
        enable_loss: true
        enable_sampling: true
        end_ckpt: 96
        num_samples: 50000
        workers: 4
      _locked: false
      _type_safe: true
    model: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _convert_dict: true
      _fields:
        attention_type: ddpm
        attn_resolutions: !!python/tuple
        - 16
        - 8
        - 4
        beta_max: 20.0
        beta_min: 0.1
        ch_mult: !!python/tuple
        - 1
        - 1
        - 2
        - 2
        - 3
        checkpoint_path: null
        conditional: true
        conv_size: 3
        dropout: 0.1
        ema_rate: 0.999
        embedding_type: fourier
        fir: true
        fir_kernel:
        - 1
        - 3
        - 3
        - 1
        fourier_scale: 16
        init_scale: 0.0
        input_channels: 3
        name: ddpm
        nf: 96
        nonlinearity: swish
        normalization: GroupNorm
        num_res_blocks: 2
        num_scales: 1000
        output_channels: 3
        progressive: output_skip
        progressive_combine: sum
        progressive_input: input_skip
        resamp_with_conv: true
        resblock_type: biggan
        scale_by_sigma: true
        sigma_max: !!python/object/apply:numpy.core.multiarray.scalar
        - !!python/object/apply:numpy.dtype
          args:
          - f8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - !!binary |
          qkxY6Hq2W0A=
        sigma_min: 0.01
        skip_rescale: true
      _locked: false
      _type_safe: true
    optim: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _convert_dict: true
      _fields:
        beta1: 0.9
        eps: 1.0e-08
        grad_clip: 1
        lr: 0.0002
        optimizer: Adam
        warmup: 0
        weight_decay: 0
      _locked: false
      _type_safe: true
    sampling: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _convert_dict: true
      _fields:
        corrector: langevin
        method: pc
        n_steps_each: 1
        noise_removal: true
        predictor: reverse_diffusion
        probability_flow: false
        snr: 0.16
      _locked: false
      _type_safe: true
    seed: 42
    training: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _convert_dict: true
      _fields:
        accelerator: null
        accumulate_grad_batches: 1
        batch_size: 50
        continuous: true
        eval_freq: 2500
        gpus: 1
        lightning_module: base
        likelihood_weighting: true
        log_freq: 250
        n_iters: 2400001
        num_epochs: 10000
        num_nodes: 1
        reduce_mean: false
        sde: vesde
        show_evolution: false
        snapshot_freq: 5000
        snapshot_freq_for_preemption: 5000
        snapshot_sampling: true
        visualization_callback: base
        workers: 4
      _locked: false
      _type_safe: true
    validation: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _convert_dict: true
      _fields:
        batch_size: 500
        workers: 4
      _locked: false
      _type_safe: true
  _locked: false
  _type_safe: true
